
export type TimeEntry = {
    id: string,
    type: string,
    date: string,
    start_plus_pause_time: null | number | string,
    start_time: null | number | string,
    stop_time: null | number | string,
    timezone: string,
    pause: number,
    pause_str: string,
    duration: number,
    duration_str: string,
    hours: number,
    minutes: number,
    comment: string,
    labels: string[] | number[],
    contract_id: null | number | string,
    hourly_wage_category: string,
    hourly_wage: number,
    amount: number,
    currency: string,
    project_id: string,
    project_name: string,
    project_identifier: string,
    project_activity: null | number | string,
    needs_approval: boolean,
    approved: boolean,
    invoiced: boolean
}